In [129]:
import pandas as pd
import numpy as np

In [130]:
n = 4
H = np.zeros([n, n-1], dtype=float)
V = np.zeros([n-1, n], dtype=float)

In [133]:
H = np.array([[2.74, 1.16, 0.73], 
              [1.43, 0, 0],
              [0, 0, 0],
              [0.73, 1.43, 2.74]])
H

array([[2.74, 1.16, 0.73],
       [1.43, 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.73, 1.43, 2.74]])

In [135]:
V = np.array([[2.90, 1.59, 0, 0.73], 
              [1.47, 0, 0, 1.75],
              [0.73, 0, 0, 2.90]])
V

array([[2.9 , 1.59, 0.  , 0.73],
       [1.47, 0.  , 0.  , 1.75],
       [0.73, 0.  , 0.  , 2.9 ]])

In [141]:
hi = 0
hj = 0
vi = 0
vj = 0


In [147]:
print(H[hi][hj])
print(V[vi][vj] - V[vi+1][vj])
h = H[hi][hj] + (H[hi][hj] - H[hi][hj+1])
h

2.74
1.43


4.32

In [148]:
print(V[vi][vj])
print(H[hi][hj] - H[hi][hj+1])
v = V[vi][vj] + (V[vi][vj] - V[vi+1][vj])
v

2.9
1.5800000000000003


4.33

In [ ]:
def up_down():
    for

In [150]:
H = np.array([[2.74, 1.16, 0.73], 
              [1.43, 0, 0],
              [0, 0, 0],
              [0.73, 1.43, 2.74]])
H

array([[2.74, 1.16, 0.73],
       [1.43, 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.73, 1.43, 2.74]])

In [149]:
V = np.array([[2.90, 1.59, 0, 0.73], 
              [1.47, 0, 0, 1.75],
              [0.73, 0, 0, 2.90]])
V

array([[2.9 , 1.59, 0.  , 0.73],
       [1.47, 0.  , 0.  , 1.75],
       [0.73, 0.  , 0.  , 2.9 ]])

In [152]:
for i in range(n-2):
    # print(H[0][i], H[0][i+1])
    V[0][i+1] = H[0][i] -  H[0][i+1]
    # print(V[0][i+1])
V

array([[2.9 , 1.58, 0.43, 0.73],
       [1.47, 0.  , 0.  , 1.75],
       [0.73, 0.  , 0.  , 2.9 ]])

In [157]:
j = 0
for i in range(n-1):
    print(H[j][i], V[j][i+1], V[j][i])
    H[j+1][i] = H[j][i] + V[j][i+1] - V[j][i]
H

2.74 1.5800000000000003 2.9
1.16 0.42999999999999994 1.5800000000000003
0.73 0.73 0.42999999999999994


array([[2.74, 1.16, 0.73],
       [1.42, 0.01, 1.03],
       [0.  , 0.  , 0.  ],
       [0.73, 1.43, 2.74]])

In [158]:
for i in range(n-2):
    # print(H[0][i], H[0][i+1])
    V[1][i+1] = H[1][i] -  H[1][i+1]
    # print(V[0][i+1])
V

array([[ 2.9 ,  1.58,  0.43,  0.73],
       [ 1.47,  1.41, -1.02,  1.75],
       [ 0.73,  0.  ,  0.  ,  2.9 ]])

In [80]:
path = 'C:\\Users\\marim\\Desktop\\summer 2024 projects\\internship 2024\\data\\'

df = pd.read_csv(path + "BrokenH11_perimeter.csv") # read from csv FileExistsError

In [81]:
df

node1 node2   voltage letters
0    N00   N01  2.741082      AB
1    N01   N02  1.155879      BC
2    N02   N03  0.726552      CD
3    N03   N13  0.726552      DE
4    N13   N23  1.750329      EF
5    N23   N33  2.899602      FG
6    N32   N33  2.741082      HG
7    N31   N32  1.433289      IH
8    N30   N31  0.726552      JI
9    N20   N30  0.726552      KJ
10   N10   N20  1.472919      LK
11   N00   N10  2.899602      AL

In [120]:
n = 4
H = np.zeros([n, n-1], dtype=float)
# V = np.zeros([n, n-1], dtype=float)
V = np.zeros([n-1, n], dtype=float)
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
#This is made by hand!!! I will write a code to make it automaticly later
H[0] = [2.74, 1.16, 0.73]
# V[3] = [0.73, 1.75, 2.90]
H[3] = [0.73, 1.43, 2.74]
# V[0] = [2.90, 1.47, 0.73]
V = np.array([[2.90, 0, 0, 0.73], 
                 [1.47, 0, 0, 1.75],
                 [0.73, 0, 0, 2.90]])

In [122]:
H

array([[2.74, 1.16, 0.73],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.73, 1.43, 2.74]])

In [123]:
V

array([[2.9 , 0.  , 0.  , 0.73],
       [1.47, 0.  , 0.  , 1.75],
       [0.73, 0.  , 0.  , 2.9 ]])

In [124]:
for i in range(n-2):
    print(H[0][i], H[0][i+1])
    V[0][i+1] = H[0][i] -  H[0][i+1]
    print(V[0][i+1])
V

2.74 1.16
1.5800000000000003
1.16 0.73
0.42999999999999994


array([[2.9 , 1.58, 0.43, 0.73],
       [1.47, 0.  , 0.  , 1.75],
       [0.73, 0.  , 0.  , 2.9 ]])

In [125]:
for i in range(n-2):
    print(V[i][0], V[i+1][0])
    H[i+1][0] = V[i][0] - V[i+1][0]
    print(H[i+1][0])
H

2.9 1.47
1.43
1.47 0.73
0.74


array([[2.74, 1.16, 0.73],
       [1.43, 0.  , 0.  ],
       [0.74, 0.  , 0.  ],
       [0.73, 1.43, 2.74]])

In [126]:
for i in range(n):
    for j in range(n-1):
        if H[i][j] == 0:
            print(i, j)

1 1
1 2
2 1
2 2


In [89]:
for i in range(n-2):
    # print(H[3][i], H[0][i+1])
    V[2][i+1] = H[3][i] -  H[3][i+1]
    print(V[2][i+1])
V

-0.7
-1.3100000000000003


array([[ 2.9 ,  1.58,  0.43,  0.73],
       [ 1.47,  0.  ,  0.  ,  1.75],
       [ 0.73, -0.7 , -1.31,  2.9 ]])

In [95]:
for i in range(n-1):
    print(V[0][i], V[0][i+1])
    H[1][i] = V[0][i] -  V[0][i+1]
    print(H[1][i])
H

2.9 1.5800000000000003
1.3199999999999996
1.5800000000000003 0.42999999999999994
1.1500000000000004
0.42999999999999994 0.73
-0.30000000000000004


array([[ 2.74,  1.16,  0.73],
       [ 1.32,  1.15, -0.3 ],
       [ 0.  ,  0.  ,  0.  ],
       [ 0.73,  1.43,  2.74]])

In [72]:
for i in range(n-2):
    print(V[3][i], V[3][i+1])
    H[i+1][2] = V[3][i] -  V[3][i+1]
    print(H[i+1][2])
H

0.73 1.75
-1.02
1.75 2.9
-1.15


array([[ 2.74,  1.16,  0.73],
       [ 1.43,  0.  , -1.02],
       [ 0.74,  0.  , -1.15],
       [ 0.73,  1.43,  2.74]])

In [73]:
for i in range(1, n-3):
    print(i)
    # print(H[0][i], H[0][i+1])
    # V[i+1][0] = H[0][i] -  H[0][i+1]
    # print(V[i+1][0])
V

array([[ 2.9 ,  1.47,  0.73],
       [ 1.58,  0.  , -0.7 ],
       [ 0.43,  0.  , -1.31],
       [ 0.73,  1.75,  2.9 ]])